version: "2.3"

services:
    postgres:
        container_name: uservice-dynconf-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=uservice_dynconf
          - POSTGRES_USER=uservice_dynconf
          - POSTGRES_PASSWORD=password
        ports:
          - 6432:5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    uservice-dynconf-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v1
        privileged: true
        environment:
          - POSTGRES_DB=uservice_dynconf
          - POSTGRES_USER=uservice_dynconf
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/uservice-dynconf/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
          - CMAKE_OPTIONS
        volumes:
          - .:/uservice-dynconf:rw
          - ./third_party/userver/tools/docker:/tools:ro
        ports:
          - 8083:8083
        working_dir: /uservice-dynconf
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
